import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :drink_water, DrinkWaterWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :drink_water, DrinkWaterWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/api/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Structured JSON logging to stdout for production log aggregation
config :logger, :default_handler,
  formatter: {LoggerJSON.Formatters.Basic, metadata: [:request_id, :user_id]}

# Sentry error tracking (DSN overridden by SENTRY_DSN env var in runtime.exs)
config :sentry,
  dsn:
    "https://062c4109173de7dfcb71aa7d0fd36690@o4511067883044864.ingest.us.sentry.io/4511067890319360",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]

# Disable PromEx metrics_server in prod (expose via authenticated Plug instead)
config :drink_water, DrinkWater.PromEx, metrics_server: :disabled

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
